### ISSUE TITLE
Gitbash turns gibberish while activating environment 

### ISSUE THREAD

**Issue by alex-christopher** [c17hawke/IPYNBrenderer#8]
Everything is working fine except the part when I try to activate the created environment the git bash terminal turns gibberish. Environment is being created and its getting activated but the screen turns this way. 
![2022-12-16](https://user-images.githubusercontent.com/91432059/208091254-3b3f1750-77d8-4763-8141-ec848f4a52a1.png)

**Comment by c17hawke** [comment]
Hi Alex,

Kindly run the following commands after starting a fresh git bash terminal and then try again - 

```bash
rm ~/.condarc
conda config --set env_prompt '({name})'
```
